# Generated by Django 4.1.7 on 2024-02-18 15:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instructor', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuizAnswar',
            new_name='QuizAnswer',
        ),
    ]
