# Generated by Django 4.1.7 on 2024-02-11 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AskedQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.learnerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='AnswarQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answar', models.TextField()),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.instructorprofile')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learner.askedquestion')),
            ],
        ),
    ]
