# Generated by Django 4.1.7 on 2024-02-11 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('learner', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AnswarQuestion',
            new_name='AnswerQuestion',
        ),
        migrations.RenameField(
            model_name='answerquestion',
            old_name='answar',
            new_name='answer',
        ),
    ]
